//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SitemapIndex = newSitemapIndexTable("public", "sitemap_index", "")

type sitemapIndexTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	EntityID     postgres.ColumnString
	UploadID     postgres.ColumnString
	RobotsID     postgres.ColumnString
	OriginID     postgres.ColumnString
	URL          postgres.ColumnString
	LastModified postgres.ColumnTimestampz
	Scraped      postgres.ColumnBool
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SitemapIndexTable struct {
	sitemapIndexTable

	EXCLUDED sitemapIndexTable
}

// AS creates new SitemapIndexTable with assigned alias
func (a SitemapIndexTable) AS(alias string) *SitemapIndexTable {
	return newSitemapIndexTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SitemapIndexTable with assigned schema name
func (a SitemapIndexTable) FromSchema(schemaName string) *SitemapIndexTable {
	return newSitemapIndexTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SitemapIndexTable with assigned table prefix
func (a SitemapIndexTable) WithPrefix(prefix string) *SitemapIndexTable {
	return newSitemapIndexTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SitemapIndexTable with assigned table suffix
func (a SitemapIndexTable) WithSuffix(suffix string) *SitemapIndexTable {
	return newSitemapIndexTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSitemapIndexTable(schemaName, tableName, alias string) *SitemapIndexTable {
	return &SitemapIndexTable{
		sitemapIndexTable: newSitemapIndexTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newSitemapIndexTableImpl("", "excluded", ""),
	}
}

func newSitemapIndexTableImpl(schemaName, tableName, alias string) sitemapIndexTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		EntityIDColumn     = postgres.StringColumn("entity_id")
		UploadIDColumn     = postgres.StringColumn("upload_id")
		RobotsIDColumn     = postgres.StringColumn("robots_id")
		OriginIDColumn     = postgres.StringColumn("origin_id")
		URLColumn          = postgres.StringColumn("url")
		LastModifiedColumn = postgres.TimestampzColumn("last_modified")
		ScrapedColumn      = postgres.BoolColumn("scraped")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, EntityIDColumn, UploadIDColumn, RobotsIDColumn, OriginIDColumn, URLColumn, LastModifiedColumn, ScrapedColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{EntityIDColumn, UploadIDColumn, RobotsIDColumn, OriginIDColumn, URLColumn, LastModifiedColumn, ScrapedColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return sitemapIndexTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EntityID:     EntityIDColumn,
		UploadID:     UploadIDColumn,
		RobotsID:     RobotsIDColumn,
		OriginID:     OriginIDColumn,
		URL:          URLColumn,
		LastModified: LastModifiedColumn,
		Scraped:      ScrapedColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
