//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Robots struct {
	ID        uuid.UUID `sql:"primary_key"`
	EntityID  uuid.UUID
	UploadID  uuid.UUID
	Data      string
	Scraped   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
